from pathlib import Path

FILES = {
    "main": "html/main.html",
}

MAIN_TEMPLATE = """
#ifndef __HTML_H__
#define __HTML_H__

#include <Arduino.h>

/* This file is automatically generated by gen_html.py */

%(content)s

#endif // __HTML_H__
"""

FILE_TEMPLATE = """
extern const char PAGE_%(name)s[] PROGMEM = R"=====(
%(content)s
)=====";
"""

def make_html(page_name, content):
    return FILE_TEMPLATE % {
        "name": page_name,
        "content": content,
    }

expanded = []
for page_name, file_path in FILES.items():
    content = Path(file_path).read_text()
    expanded.append(make_html(page_name.upper(), content))

with open("src/html/html.h", "w") as f:
    f.write((MAIN_TEMPLATE % {
        "content": "\n".join(expanded)
    }).strip())
